#!/bin/bash

#$PWD/prep-trema
$PWD/ovs-start

INTERFACES="192.168.1.1 192.168.2.1 192.168.3.1"

#create a file /tmp/ifmap containing eth1 192.168.1.1 mac
./writeifmap3

$PWD/find-interfaces $INTERFACES | while read iface; do
    ovs-vsctl add-port br0 $iface < /dev/null
done

ovs-ofctl show tcp:127.0.0.1:6634 \
    | ./ovs-id-ports 192.168.1.1=outside 192.168.2.1=left 192.168.3.1=right \
    > /tmp/portmap
