#!/bin/sh

OVSROOT=/opt/openvswitch-1.6.1-F15

$PWD/sudo-setup

DOSUDO=$PWD/dosudo

$DOSUDO $PWD/prep-trema
$DOSUDO $PWD/ovs-init
$DOSUDO $PWD/ovs-start

$PWD/find-interfaces 192.168.128.1 192.168.129.1 | while read iface; do
    $DOSUDO $OVSROOT/bin/ovs-vsctl add-port br0 $iface < /dev/null
done
