#!/bin/bash

/tmp/of-topo-setup/writeifmap

ovs-vsctl add-br br0

INTERFACES="$1 $2"

echo $INTERFACES
/tmp/of-topo-setup/find-interfaces $INTERFACES | while read iface; do
    ovs-vsctl add-port br0 $iface < /dev/null
done
#ovs-vsctl set Bridge br0 stp_enable=true

echo outside `/tmp/of-topo-setup/find-interfaces $2` > /tmp/ifmap
echo inside `/tmp/of-topo-setup/find-interfaces $1` >> /tmp/ifmap

