#! /bin/bash

echo "Stopping controller"
kill $(pidof ruby)
echo "Disconnecting switch"
ovs-vsctl del-controller br0

echo "Starting controller"
source /etc/profile.d/rvm.sh
trema run /tmp/aggregator/aggregator.rb >& /tmp/trema.run &
echo "Connecting switch"
ovs-vsctl set-controller br0 tcp:127.0.0.i:6653 ptcp:6634:127.0.0.1
echo "Done!"
