#!/bin/sh

OVSROOT=/opt/openvswitch-1.6.1-F15

mkdir -p $OVSROOT/etc/openvswitch

$OVSROOT/bin/ovsdb-tool create $OVSROOT/etc/openvswitch/conf.db \
                               $OVSROOT/share/openvswitch/vswitch.ovsschema
$OVSROOT/sbin/ovsdb-server --remote=punix:$OVSROOT/var/run/openvswitch/db.sock \
                           --remote=db:Open_vSwitch,manager_options \
                           --private-key=db:SSL,private_key \
                           --certificate=db:SSL,certificate \
                           --bootstrap-ca-cert=db:SSL,ca_cert \
                           --pidfile --detach
$OVSROOT/bin/ovs-vsctl --no-wait init
