#!/bin/bash

/tmp/of-topo-setup/writeifmap

ovs-vsctl add-br br0
ovs-vsctl set bridge br0 datapath_type=netdev

ovs-vsctl set-controller br0 tcp:127.0.0.1 ptcp:6634:127.0.0.1

ovs-vsctl add-port br0 eth1 < /dev/null
ovs-vsctl add-port br0 eth2 < /dev/null

echo outside `$PWD/find-interfaces 192.168.2.2` > /tmp/ifmap
echo inside `$PWD/find-interfaces 192.168.4.1` >> /tmp/ifmap

