#! /bin/bash

echo "Stopping controller"
kill $(pidof ruby)
rm /opt/trema-trema-f995284/tmp/pid/Aggregator.pid
echo "Disconnecting switch"
ovs-vsctl del-controller br0

echo "Starting controller"
/opt/trema-trema-f995284/trema run /tmp/aggregator/aggregator.rb >& /tmp/trema.run &
echo "Connecting switch"
ovs-vsctl set-controller br0 tcp:127.0.0.1 ptcp:6634:127.0.0.1
echo "Done!"
