#!/bin/bash

mv /tmp/trema-trema-f995284/ /opt/

source /etc/profile.d/rvm.sh
rvm use 1.8.7

/tmp/of-topo-setup/prep-trema
/tmp/of-topo-setup/ovs-start

INTERFACES="192.168.4.2 192.168.5.2 192.168.6.1"
#create a file /tmp/ifmap containig eth1 192.168.1.1 mac
/tmp/of-topo-setup/writeifmap3

/tmp/of-topo-setup/find-interfaces $INTERFACES | while read iface; do
    ovs-vsctl add-port br0 $iface < /dev/null
done

ovs-ofctl show tcp:127.0.0.1:6634 \
    | /tmp/of-topo-setup/ovs-id-ports 192.168.4.2=left 192.168.5.2=right 192.168.6.1=inside \
    > /tmp/portmap

{
    /opt/trema-trema-f995284/trema run /tmp/aggregator/aggregator.rb
} > /tmp/trema-runlog 2>&1 &
