#!/bin/bash

#wait until all interfaces are up and configured
ethnum=$(ifconfig | grep 'Link encap:' | awk '{print $1}')
while [[ "$ethnum" != *eth1* || "$ethnum" != *eth2* ]]; do
	/usr/local/bin/neuca-netconf
	sleep 10
        ethnum=$(ifconfig | grep 'Link encap:' | awk '{print $1}')
        echo $ethnum
done


linenum=0
ifconfig | grep -e "Link enca" -e "inet addr" |grep -v "127.0" | grep -v "lo" | grep -v "eth0" | grep -v "addr:10." | while read line; do
	if [ $((linenum%2)) -eq 0 ]
	then
		iface=$(echo $line | awk '{print $1}')
		mac=$(echo $line | awk '{print $5}')
	else
		ip=$(echo $line | awk '{print $2}')
	fi
	linenum=$((linenum+1))
	
	if [ $((linenum % 2)) -eq 0 ]
	then
		ip=`expr substr $ip 6 11`
		echo "$iface $ip $mac" >> /tmp/ifmap.tmp
	fi
done

