#!/bin/sh

/tmp/of-topo-setup/ovs-start

wget http://www.gpolab.bbn.com/experiment-support/OpenFlowExampleExperiment/ExoGENI/load-balancer.rb -O /root/load-balancer.rb

INTERFACES="$1 $2 $3"

#create a file /tmp/ifmap containing eth1 192.168.1.1 mac
/tmp/of-topo-setup/writeifmap3

/tmp/of-topo-setup/find-interfaces $INTERFACES | while read iface; do
    ovs-vsctl add-port br0 $iface < /dev/null
done

ovs-ofctl show tcp:127.0.0.1:6634 \
    | /tmp/of-topo-setup/ovs-id-ports $1=outside $2=left $3=right \
    > /tmp/portmap
