#!/bin/sh

/tmp/of-topo-setup/ovs-start
cp /tmp/of-topo-setup/ofcollect.rb /usr/local/bin/ofcollect.rb

ln -s /tmp/load-balancer/load-balancer.rb /root/load-balancer.rb 

INTERFACES="$1 $2 $3"

#create a file /tmp/ifmap containing eth1 192.168.1.1 mac
/tmp/of-topo-setup/writeifmap3

/tmp/of-topo-setup/find-interfaces $INTERFACES | while read iface; do
    ovs-vsctl add-port br0 $iface < /dev/null
done

ovs-ofctl show tcp:127.0.0.1:6633 \
    | /tmp/of-topo-setup/ovs-id-ports $1=outside $2=left $3=right \
    > /tmp/portmap
